[tool.isort]
line_length = 100
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
ensure_newline_before_comments = true
lines_between_sections = true
skip = [".venv", "venv", "deploy", ".git", ".github"]
extend_skip = [".md", ".json"]
src_paths = ['']

[tool.black]
line-length = 100
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
(
      \.git
    | \.gitignore
    | \.github
    | \.venv
    | \venv
    | \.pytest_cache
    | \.deploy
)
'''
