app:
  window_title: "Simple Video Tagger"
  default_volume: 80
  font:
    name: "Menlo"
    size: 12

tags:
  - name: JUM H
    color: "#FF0000"
    shortcut: E
  - name: JUM M
    color: "#0000FF"
    shortcut: W
  - name: JUM L
    color: "#FFA500"
    shortcut: Q
  - name: DIV L
    color: "#00FFFF"
    shortcut: Z
  - name: DIV R
    color: "#00FF00"
    shortcut: C
  - name: DIV F
    color: "#964B00"
    shortcut: S
  - name: DIV B
    color: "#550000"
    shortcut: X
